package irt.calibration.tools.unit.packets.enums;

public enum PacketType {
	SPONTANEOUS((byte) 0x0),		/* Spontaneous message, generated by device. */
	RESPONSE	((byte) 0x1),		/* Response, generated as response to command or status request. */
	REQUEST		((byte) 0x2),		/* Status request. */
	COMMAND		((byte) 0x3),		/* Command. */
	ACK			((byte) 0xFF);		/* Layer 2 acknowledgement. */

	private final byte type;

	private PacketType(byte type) {
		this.type = type;
	}

	public byte toByte() {
		return type;
	}
}
